name: twitter_extractor
description: This plugin lets you download tweets
version: 0.0.1
repository: https://github.com/TamilKannanCV-personal/twitter_extractor.git

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.example.twitter_extractor
        pluginClass: TwitterExtractorPlugin
